apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "verse-store.fullname" . }}-app
  labels:
    {{- include "verse-store.labels" . | nindent 4 }}
data:
  SPRING_PROFILES_ACTIVE: kubernetes
  DATABASE_URL: jdbc:postgresql://{{ include "verse-store.fullname" . }}-postgres:5432/{{ .Values.postgres.database }}
  DATABASE_USERNAME: {{ .Values.postgres.username | quote }}
  KEYCLOAK_ISSUER_URI: {{ printf "%s/realms/verse" .Values.keycloak.publicBaseUrl | quote }}
  KEYCLOAK_AUTHORIZATION_URI: {{ printf "%s/realms/verse/protocol/openid-connect/auth" .Values.keycloak.publicBaseUrl | quote }}
  KEYCLOAK_TOKEN_URI: {{ printf "http://%s-keycloak:8080/realms/verse/protocol/openid-connect/token" (include "verse-store.fullname" .) | quote }}
  KEYCLOAK_USER_INFO_URI: {{ printf "http://%s-keycloak:8080/realms/verse/protocol/openid-connect/userinfo" (include "verse-store.fullname" .) | quote }}
  KEYCLOAK_JWK_SET_URI: {{ printf "http://%s-keycloak:8080/realms/verse/protocol/openid-connect/certs" (include "verse-store.fullname" .) | quote }}
  KEYCLOAK_PUBLIC_BASE_URL: {{ .Values.keycloak.publicBaseUrl | quote }}
  KEYCLOAK_POST_LOGOUT_REDIRECT_URI: {{ printf "%s/" .Values.app.publicBaseUrl | quote }}
  PRODUCT_IMAGE_STORAGE_ENDPOINT: {{ printf "http://%s-minio:9000" (include "verse-store.fullname" .) | quote }}
  PRODUCT_IMAGE_BUCKET: {{ .Values.minio.bucket | quote }}
  JAVA_TOOL_OPTIONS: "-XX:MaxRAMPercentage=75.0 -XX:+ExitOnOutOfMemoryError"

