spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    enabled: true
  security:
    oauth2:
      client:
        provider:
          keycloak:
            token-uri: http://keycloak:8080/realms/verse/protocol/openid-connect/token
            user-info-uri: http://keycloak:8080/realms/verse/protocol/openid-connect/userinfo
            jwk-set-uri: http://keycloak:8080/realms/verse/protocol/openid-connect/certs
      resourceserver:
        jwt:
          jwk-set-uri: http://keycloak:8080/realms/verse/protocol/openid-connect/certs
  lifecycle:
    timeout-per-shutdown-phase: 30s

management:
  endpoint:
    health:
      probes:
        enabled: true
      show-details: never

server:
  shutdown: graceful
